name: Build Android APK
on:
  push:
    branches: [ main ]
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install system deps
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip build-essential
      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython
      - name: Build APK
        working-directory: build
        run: |
          buildozer -v android debug
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jewelryapp-apk
          path: build/bin/*.apk
